initial update for v 5.3.2
conda-forge/celery-feedstock pull request #64
Opened 2022-01-19 18:30 UTC by AdMax18

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2022-01-19 18:30 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-01-31 20:27 UTC, AdMax18 commented
@conda-forge-admin, please rerender

2022-01-31 20:40 UTC, AdMax18 commented
bumping for review and merge @igortg @kwilcox  @mcs07

2022-02-04 12:48 UTC, chrisburr requested changes

2022-02-04 12:48 UTC, chrisburr commented on recipe/meta.yaml
>  test:
Can you add the tests back here?

2022-02-07 15:47 UTC, AdMax18 commented
@conda-forge-admin, please rerender

2022-02-07 16:22 UTC, AdMax18 commented
@conda-forge-admin, please rerender

2022-02-07 19:27 UTC, chrisburr commented
Thanks @AdMax18! 🍰

2022-02-07 19:27 UTC, merged